import {StyleSheet} from 'react-native';
import {Fonts} from '../../styles/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  headerWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: '11%',
    paddingBottom: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e8f4f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#111827',
  },
  buttonContainer: {
    marginTop: 10,
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    elevation: 5,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  contactButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F4F7',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#58D163',
    marginRight: 8,
  },
  contactButtonText: {
    color: '#34C759',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 10,
    marginLeft: 8,
  },
  checkoutButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0088B1',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
    flexDirection: 'row',
    gap: 5,
  },
  checkoutButtonText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: Fonts.JakartaSemiBold,
  },
  // New styles added below
  orderInfoContainer: {
    flex: 1,
    backgroundColor: '#E8F4F7',
    padding: 12,
    borderRadius: 12,
  },
  orderInfoBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E8E9',
  },
  orderInfoText: {
    fontSize: 11,
    marginTop: 5,
    fontFamily: Fonts.JakartaRegular,
  },
  orderInfoLabel: {
    fontSize: 11,
    marginTop: 5,
    fontFamily: Fonts.JakartaRegular,
    color: '#667085',
  },
  deliveryEstimate: {
    color: '#12B76A',
    fontSize: 11,
    fontFamily: Fonts.JakartaRegular,
  },
  orderItemsHeader: {
    fontSize: 14,
    fontFamily: Fonts.JakartaRegular,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 10,
    marginTop: 20,
    padding: 16,
    borderRadius: 12,
  },
  summaryTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaBold,
    marginBottom: 16,
    color: '#000000',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#667085',
  },
  summaryValue: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#000000',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  totalText: {
    fontSize: 10,
    fontFamily: Fonts.JakartaBold,
    color: '#000000',
  },
  addressCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 10,
    marginTop: 20,
    padding: 16,
    borderRadius: 12,
  },
  addressTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaBold,
    marginLeft: 8,
    color: '#000000',
  },
  customerName: {
    fontSize: 10,
    fontFamily: Fonts.JakartaBold,
    marginBottom: 8,
    color: '#000000',
  },
  customerAddress: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#667085',
    lineHeight: 20,
    marginBottom: 8,
  },
  paymentCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 10,
    marginTop: 20,
    padding: 16,
    borderRadius: 12,
  },
  paymentTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaBold,
    marginLeft: 8,
    color: '#000000',
  },
  cancelButton: {
    backgroundColor: '#FEF2F2',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 20,
    padding: 10,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FEE2E2',
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: Fonts.JakartaRegular,
    color: '#EF4444',
  },
});

export default styles;
