import {Platform, StatusBar, StyleSheet} from 'react-native';
import {FontColors, Fonts} from '../../styles/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: FontColors.tertiary,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    gap: 10,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: FontColors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: FontColors.textBlack,
  },
  buttonContainer: {
    marginTop: 10,
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 16,
    paddingBottom: Platform.OS === 'android' ? 48 : 16,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    elevation: 5,
    shadowColor: FontColors.textBlack,
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  contactButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FontColors.secondary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#58D163',
    marginRight: 8,
  },
  contactButtonText: {
    color: '#34C759',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 12,
    marginLeft: 8,
  },
  checkoutButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FontColors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginLeft: 8,
    flexDirection: 'row',
    gap: 5,
  },
  checkoutButtonText: {
    color: FontColors.tertiary,
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
  },
  // New styles added below
  orderInfoContainer: {
    flex: 1,
    backgroundColor: FontColors.secondary,
    gap: 8,
    padding: 12,
    borderRadius: 12,
  },
  orderInfoBorder: {
    borderBottomWidth: 0.8,
    borderBottomColor: '#bec1c1ff',
    paddingBottom: 8,
  },
  orderInfoText: {
    fontSize: 10,
    marginTop: 5,
    fontFamily: Fonts.JakartaRegular,
  },
  orderInfoLabel: {
    fontSize: 11,
    marginTop: 5,
    fontFamily: Fonts.JakartaRegular,
    color: '#667085',
  },
  deliveryEstimate: {
    color: '#12B76A',
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
  },
  OrderCancelled: {
    color: '#EB5757',
    fontSize: 11,
    fontFamily: Fonts.JakartaRegular,
  },
  orderItemsHeader: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 24,
    marginTop: 32,
    padding: 12,
    borderRadius: 10,
    borderColor: '#E5E8E9',
    borderWidth: 1,
  },
  summaryTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    marginBottom: 16,
    color: FontColors.textBlack,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#667085',
  },
  phoneText: {
    fontFamily: Fonts.JakartaMedium,
    fontSize: 12,
  },
  summaryValue: {
    fontSize: 10,
    fontFamily: Fonts.JakartaMedium,
    color: FontColors.textBlack,
  },
  discountLabel: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#50B57F',
  },
  discountValue: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#50B57F',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  totalText: {
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
    color: FontColors.textBlack,
  },
  addressCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 24,
    marginTop: 16,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E8E9',
  },
  addressTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaBold,
    color: FontColors.textBlack,
  },
  customerName: {
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
    marginBottom: 4,
    color: FontColors.textBlack,
  },
  customerAddress: {
    fontSize: 12,
    fontFamily: Fonts.JakartaRegular,
    color: '#667085',
    marginBottom: 4,
  },
  paymentCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 24,
    marginTop: 16,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E8E9',
  },
  paymentTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    marginLeft: 8,
    color: FontColors.textBlack,
  },
  cancelButton: {
    backgroundColor: '#FFEAEA',
    marginHorizontal: 24,
    marginBottom: 10,
    marginTop: 24,
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E8E9',
  },
  cancelButtonText: {
    fontSize: 14,
    fontFamily: Fonts.JakartaMedium,
    color: '#EB5757',
  },
});

export default styles;
