import { StyleSheet } from 'react-native';
import { Fonts } from '../../styles/fonts';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f9fafb',
    flex: 1,
  },
  headerWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '11%',
    paddingBottom: 10,
    paddingHorizontal: 20,
  },
  headerLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#e8f4f7',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  headerTitle: {
    color: '#111827',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 16,
  },
  buttonContainer: {
    backgroundColor: '#FFFFFF',
    borderTopColor: '#E0E0E0',
    borderTopWidth: 1,
    bottom: 0,
    elevation: 5,
    flexDirection: 'column',
    left: 0,
    marginTop: 10,
    padding: 16,
    paddingBottom: 24,
    right: 0,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  contactButton: {
    alignItems: 'center',
    backgroundColor: '#E8F4F7',
    borderColor: '#58D163',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  contactButtonText: {
    color: '#34C759',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 10,
    marginLeft: 8,
  },
  checkoutButton: {
    alignItems: 'center',
    backgroundColor: '#0088B1',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    marginLeft: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  checkoutButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 10,
  },
  // New styles added below
  orderInfoContainer: {
    backgroundColor: '#E8F4F7',
    borderRadius: 12,
    flex: 1,
    padding: 12,
  },
  orderInfoBorder: {
    borderBottomColor: '#E5E8E9',
    borderBottomWidth: 1,
  },
  orderInfoText: {
    fontFamily: Fonts.JakartaRegular,
    fontSize: 11,
    marginTop: 5,
  },
  orderInfoLabel: {
    color: '#667085',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 11,
    marginTop: 5,
  },
  deliveryEstimate: {
    color: '#12B76A',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 11,
  },
  orderItemsHeader: {
    fontFamily: Fonts.JakartaRegular,
    fontSize: 14,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginHorizontal: 10,
    marginTop: 20,
    padding: 16,
  },
  summaryTitle: {
    color: '#000000',
    fontFamily: Fonts.JakartaBold,
    fontSize: 14,
    marginBottom: 16,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  summaryLabel: {
    color: '#667085',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
  },
  summaryValue: {
    color: '#000000',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
  },
  totalRow: {
    borderTopColor: '#E5E7EB',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
  },
  totalText: {
    color: '#000000',
    fontFamily: Fonts.JakartaBold,
    fontSize: 10,
  },
  addressCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginHorizontal: 10,
    marginTop: 20,
    padding: 16,
  },
  addressTitle: {
    color: '#000000',
    fontFamily: Fonts.JakartaBold,
    fontSize: 14,
    marginLeft: 8,
  },
  customerName: {
    color: '#000000',
    fontFamily: Fonts.JakartaBold,
    fontSize: 10,
    marginBottom: 8,
  },
  customerAddress: {
    color: '#667085',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
    lineHeight: 20,
    marginBottom: 8,
  },
  paymentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginHorizontal: 10,
    marginTop: 20,
    padding: 16,
  },
  paymentTitle: {
    color: '#000000',
    fontFamily: Fonts.JakartaBold,
    fontSize: 14,
    marginLeft: 8,
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    borderColor: '#FEE2E2',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginHorizontal: 10,
    marginTop: 20,
    padding: 10,
  },
  cancelButtonText: {
    color: '#EF4444',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 16,
  },
});

export default styles;
