import { Dimensions, StyleSheet } from 'react-native';
import { Fonts } from '../../../styles/fonts';

export const styles = StyleSheet.create({
  activeDot: {
    backgroundColor: '#899193',
  },
  addCartButton: {
    backgroundColor: '#0088B1',
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  buttonText: {
    color: '#fff',
    fontFamily: Fonts.JakartaSemiBold,
    textAlign: 'center',
  },
  consultButton: {
    alignItems: 'center',
    backgroundColor: '#E8F4F7',
    borderColor: '#0088B1',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  consultButtonText: {
    color: '#0088B1',
    fontFamily: Fonts.JakartaSemiBold,
    marginLeft: 8,
  },
  container: {
    backgroundColor: '#fff',
    flex: 1,
  },
  currentPrice: {
    color: '#333',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 22,
  },
  deliveryText: {
    color: '#50B57F',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 14,
  },
  disabledButton: {
    backgroundColor: '#787a79',
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  discount: {
    color: '#4CAF50',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
    marginLeft: 8,
  },
  dot: {
    backgroundColor: '#ccc',
    borderRadius: 4,
    height: 8,
    marginHorizontal: 4,
    width: 8,
  },
  dotIndicatorContainer: {
    flexDirection: 'row',
  },
  emptyImageContainer: {
    alignItems: 'center',
    backgroundColor: '#E8E8E8',
    justifyContent: 'center',
  },
  emptyImageText: {
    color: '#888888',
    fontFamily: Fonts.JakartaMedium,
    fontSize: 16,
  },
  icon: {
    height: 16,
    tintColor: '#0088B1',
    width: 16,
  },
  image: {
    height: '100%',
    resizeMode: 'contain',
    width: Dimensions.get('window').width,
  },
  imageContainer: {
    height: 250,
    position: 'relative',
    width: '100%',
  },
  inStock: {
    color: '#50B57F',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
  },
  medicineName: {
    color: '#333',
    fontFamily: Fonts.JakartaBold,
    fontSize: 22,
  },
  medicinePack: {
    color: '#666',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 14,
    marginTop: 4,
  },
  nameContainer: {
    marginTop: 12,
    paddingHorizontal: 16,
  },
  originalPrice: {
    color: '#999',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 16,
    marginLeft: 8,
    textDecorationLine: 'line-through',
  },
  priceContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 16,
    paddingHorizontal: 16,
  },
  ratingContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 16,
  },
  saltComposition: {
    color: '#666',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 14,
    marginTop: 4,
    paddingHorizontal: 16,
  },
  saltLabel: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 16,
    paddingHorizontal: 16,
  },
  starsContainer: {
    flexDirection: 'row',
  },
  stockContainer: {
    alignItems: 'center',
    borderColor: '#50B57F',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 16,
    padding: 16,
  },
});
