import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';
import { Fonts } from '../../styles/fonts';

const { width } = Dimensions.get('window');
const ITEM_WIDTH = (width - 48) / 3; // 16px padding on each side + 8px gap between items

export const styles = StyleSheet.create({
  backButton: {
    alignItems: 'center',
    backgroundColor: '#e8f4f7',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  container: {
    backgroundColor: '#fff',
    flex: 1,
    padding: 16,
  },
  description: {
    color: '#899193',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 14,
    marginBottom: 12,
  },
  estimatedTime: {
    color: '#161D1F',
    fontFamily: Fonts.JakartaBold,
    fontSize: 14,
    marginBottom: 16,
    textAlign: 'center',
  },
  exploreBtn: {
    alignItems: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    marginBottom: 50,
  },
  exploreText: {
    color: '#F8F8F8',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 12,
  },
  headerLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  headerTitle: {
    color: '#111827',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 16,
  },
  headerWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 10,

    paddingHorizontal: 20,
  },
  heading: {
    color: '#161D1F',
    fontFamily: Fonts.JakartaBold,
    fontSize: 12,
    marginBottom: 4,
    marginTop: 12,
  },
  imageThumbnail: {
    backgroundColor: '#F5FAFC',
    borderRadius: 6,
    height: 148,
    marginBottom: 8,
    width: '100%',
  },
  infoCard: {
    borderRadius: 12,
    height: 160,
    marginBottom: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    width: '100%',
  },
  infoCardText: {
    color: '#fff',
    fontFamily: Fonts.JakartaRegular,
    fontSize: Platform.OS === 'ios' ? 10 : 12,
    marginBottom: 12,
    marginRight: 16,
  },

  itemDateText: {
    color: '#6D7578',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
  },
  itemIconContainer: {
    alignItems: 'center',
    backgroundColor: '#E1F0F7',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    marginBottom: 8,
    width: 40,
  },
  itemTypeText: {
    color: '#0088B1',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 12,
    marginBottom: 4,
  },
  learnMoreRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 20,
  },
  learnMoreText: {
    color: '#6D7578',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
    marginRight: 4,
  },
  noDataContainer: {
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    borderColor: '#e0e0e0',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginVertical: 16,
    minHeight: 100,
    padding: 20,
  },
  noDataText: {
    color: '#6D7578',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 16,
    textAlign: 'center',
  },
  pdfIconContainer: {
    alignItems: 'center',
    backgroundColor: '#F5FAFC',
    borderRadius: 6,
    height: 148,
    justifyContent: 'center',
    marginBottom: 8,
    padding: 10,
    width: '100%',
  },
  prescriptionItem: {
    alignItems: 'center',
    borderColor: '#0088B1',
    borderRadius: 8,
    borderWidth: 1,
    height: 180,
    justifyContent: 'center',
    marginBottom: 12,
    padding: 8,
    width: ITEM_WIDTH,
  },
  prescriptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  progressCircle: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: 'pink',
    borderRadius: 100,
    borderWidth: 15,
    height: 150,
    justifyContent: 'center',
    marginBottom: 20,
    width: 150,
  },
  safeArea: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: '#161D1F',
    fontFamily: Fonts.JakartaBold,
    fontSize: 16,
    marginBottom: 16,
  },
  uploadMoreButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  uploadMoreText: {
    color: '#0088B1',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
  },
  uploadText: {
    color: '#6D7578',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 12,
    marginTop: 4,
  },
  whatsappButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
});
