import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';
import { Fonts } from '../../styles/fonts';

const { width } = Dimensions.get('window');
const ITEM_WIDTH = (width - 48) / 3; // 16px padding on each side + 8px gap between items

export const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: '#fff',
    flex: 1,
  },
  safeArea: {
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,

    paddingBottom: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e8f4f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#111827',
  },
  progressCircle: {
    width: 150,
    height: 150,
    borderRadius: 100,
    borderWidth: 15,
    borderColor: 'pink',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  estimatedTime: {
    textAlign: 'center',
    fontSize: 14,
    color: '#161D1F',
    marginBottom: 16,
    fontFamily: Fonts.JakartaBold,
  },
  heading: {
    fontSize: 12,
    marginTop: 12,
    marginBottom: 4,
    color: '#161D1F',
    fontFamily: Fonts.JakartaBold,
  },
  description: {
    fontSize: 14,
    color: '#899193',
    marginBottom: 12,
    fontFamily: Fonts.JakartaRegular,
  },
  learnMoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  learnMoreText: {
    fontSize: 14,
    color: '#6D7578',
    marginRight: 4,
    fontFamily: Fonts.JakartaSemiBold,
  },
  infoCard: {
    width: '100%',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 24,
    height: 160,
  },

  infoCardText: {
    fontSize: Platform.OS === 'ios' ? 10 : 12,
    marginBottom: 12,
    marginRight: 16,
    color: '#fff',
    fontFamily: Fonts.JakartaRegular,
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.JakartaBold,
    color: '#161D1F',
    marginBottom: 16,
  },
  prescriptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  prescriptionItem: {
    width: ITEM_WIDTH,
    height: 180,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#0088B1',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  itemIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E1F0F7',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemTypeText: {
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#0088B1',
    marginBottom: 4,
  },
  itemDateText: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#6D7578',
  },
  noDataContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minHeight: 100,
  },
  noDataText: {
    fontSize: 16,
    color: '#6D7578',
    textAlign: 'center',
    fontFamily: Fonts.JakartaSemiBold,
  },
  uploadMoreButton: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  uploadMoreText: {
    fontFamily: Fonts.JakartaSemiBold,
    color: '#0088B1',
    fontSize: 14,
  },
  exploreBtn: {
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
  },
  whatsappButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exploreText: {
    color: '#F8F8F8',
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
  },
  uploadText: {
    marginTop: 4,
    fontSize: 12,
    color: '#6D7578',
    fontFamily: Fonts.JakartaRegular,
  },
  pdfIconContainer: {
    width: '100%',
    height: 148,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FAFC',
    borderRadius: 6,
    marginBottom: 8,
    padding: 10,
  },
  imageThumbnail: {
    width: '100%',
    height: 148,
    borderRadius: 6,
    marginBottom: 8,
    backgroundColor: '#F5FAFC',
  },
});
