# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_API_KEY_CONTENT"],
      in_house: false
    )

    build_app(
      scheme: "Mediversal_app",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.mediversal.mediversalapp.dev" => "MediversalAppProvisioningProfile"
        }
      }
    )

    upload_to_testflight(api_key: api_key)
  end
end


