import {Platform, StatusBar, StyleSheet} from 'react-native';
import {FontColors, Fonts} from '../../styles/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingBottom: 120,
  },
  amountLabel: {
    fontSize: 10,
    color: FontColors.textBlack,
    fontFamily: Fonts.JakartaRegular,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e8f4f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  couponStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Platform.OS === 'ios' ? 0 : 14,
    paddingVertical: Platform.OS === 'ios' ? 0 : 12,
    borderRadius: 6,
    marginHorizontal: 24,
    marginTop: 12,
    backgroundColor: FontColors.secondary,
  },
  couponLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: Platform.OS === 'ios' ? 14 : 0,
  },
  couponText: {
    fontSize: 12,
    marginLeft: 0,
    paddingVertical: Platform.OS === 'ios' ? 12 : 0,
    fontFamily: Fonts.JakartaSemiBold,
  },
  deliveryLeft: {
    padding: 6,
    backgroundColor: FontColors.secondary,
    borderRadius: 4,
  },
  icon: {
    marginRight: 0,
    color: FontColors.textBlack,
  },
  iconIOS: {
    marginRight: Platform.OS === 'ios' ? 14 : 0,
  },
  deliveryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 24,
    marginTop: 32,
    marginBottom: 12,
    gap: 10,
  },
  deliveryText: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: FontColors.textBlack,
  },
  mediCashCard: {
    height: 52,
    marginHorizontal: 24,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#B0B6B8',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F2F4F5',
    marginVertical: 32,
  },
  mediCashLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mediCashText: {
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#B0B6B8',
  },
  radioCircle: {
    height: 18,
    width: 18,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#B0B6B8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedDot: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: FontColors.primary,
  },
  radioLabel: {
    fontSize: 12,
    color: '#B0B6B8',
  },
  billSummaryLabel: {
    fontSize: 14,
    fontFamily: Fonts.JakartaMedium,
    marginHorizontal: 24,
    marginTop: 16,
    color: FontColors.textBlack,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 16,
    paddingHorizontal: 24,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amountText: {
    fontSize: 24,
    fontFamily: Fonts.JakartaBold,
    color: FontColors.primary,
  },
  addressButton: {
    backgroundColor: FontColors.primary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  addressButtonText: {
    color: FontColors.tertiary,
    fontSize: 12,
    fontFamily: Fonts.JakartaMedium,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#fff',
  },

  headerRightIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  iconSpacing: {
    marginRight: 16,
  },
  safeHeader: {
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: 'red',
    marginBottom: 20,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: FontColors.primary,
    padding: 10,
    borderRadius: 5,
  },
  retryButtonText: {
    color: 'white',
  },
  emptyCartContainer: {
    padding: 20,
    alignItems: 'center',
  },
  emptyCartText: {
    fontSize: 16,
    color: '#666',
    fontFamily: Fonts.JakartaSemiBold,
  },
  appliedCouponContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Platform.OS === 'android' ? 5 : 0,
    marginHorizontal: 20,
    backgroundColor: '#E8F4F7',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  appliedCouponLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  appliedCouponCode: {
    fontSize: 10,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#FFFFFF',
    marginLeft: 4,
  },
  appliedCouponText: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#E8F4F7',
    marginLeft: 8,
    marginTop: Platform.OS === 'ios' ? -5 : 0,
    paddingVertical: Platform.OS === 'ios' ? 5 : 0,
    marginBottom: Platform.OS === 'ios' ? 5 : 0,
  },
  removeCouponText: {
    fontSize: 10,
    fontFamily: Fonts.JakartaSemiBold,
    color: FontColors.primary,
    textDecorationLine: 'underline',
    marginRight: Platform.OS === 'ios' ? 10 : 0,
    marginBottom: Platform.OS === 'ios' ? 10 : 0,
  },
});
