import { Platform, StatusBar, StyleSheet } from 'react-native';
import { Fonts } from '../../styles/fonts';

export const styles = StyleSheet.create({
  addressButton: {
    backgroundColor: '#0088B1',
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  addressButtonText: {
    color: '#fff',
    fontFamily: Fonts.JakartaBold,
    fontSize: 10,
  },
  amountLabel: {
    color: '#161D1F',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
    marginBottom: 2,
  },
  amountText: {
    color: '#0088B1',
    fontFamily: Fonts.JakartaBold,
    fontSize: 16,
  },
  appliedCouponCode: {
    color: '#FFFFFF',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 10,
    marginLeft: 4,
  },
  appliedCouponContainer: {
    alignItems: 'center',
    backgroundColor: '#E8F4F7',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    padding: Platform.OS === 'android' ? 5 : 0,
  },
  appliedCouponLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
  },
  appliedCouponText: {
    color: '#E8F4F7',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
    marginBottom: Platform.OS === 'ios' ? 5 : 0,
    marginLeft: 8,
    marginTop: Platform.OS === 'ios' ? -5 : 0,
    paddingVertical: Platform.OS === 'ios' ? 5 : 0,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#e8f4f7',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  billSummaryLabel: {
    color: '#161D1F',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 18,
    marginHorizontal: 12,
    marginTop: 16,
  },
  bottomBar: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderTopColor: '#ccc',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    padding: 16,
    position: 'absolute',
    right: 0,
  },
  container: {
    flex: 1,
  },
  couponLeft: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  couponStrip: {
    alignItems: 'center',
    backgroundColor: '#E8F4F7',
    borderRadius: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 12,
    marginTop: 12,
    padding: Platform.OS === 'ios' ? 0 : 12,
  },
  couponText: {
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 12,
    lineHeight: 20,
    marginLeft: 6,
    paddingVertical: Platform.OS === 'ios' ? 12 : 0,
  },
  deliveryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 15,
    marginTop: 20,
  },
  deliveryText: {
    color: '#161D1F',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
    marginBottom: 5,
  },
  emptyCartContainer: {
    alignItems: 'center',
    padding: 20,
  },
  emptyCartText: {
    color: '#666',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 16,
  },
  errorContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  errorText: {
    color: 'red',
    marginBottom: 20,
    textAlign: 'center',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
  },

  headerRightIcons: {
    alignItems: 'center',
    flexDirection: 'row',
  },

  icon: {
    marginRight: 6,
  },
  iconSpacing: {
    marginRight: 16,
  },
  loadingContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  mediCashCard: {
    alignItems: 'center',
    backgroundColor: '#F2F4F5',
    borderColor: '#B0B6B8',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    height: 52,
    justifyContent: 'space-between',
    margin: 12,
    paddingHorizontal: 12,
  },
  mediCashLeft: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  mediCashText: {
    color: '#B0B6B8',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 12,
  },
  radioCircle: {
    alignItems: 'center',
    borderColor: '#B0B6B8',
    borderRadius: 10,
    borderWidth: 2,
    height: 20,
    justifyContent: 'center',
    marginRight: 6,
    width: 20,
  },
  radioLabel: {
    color: '#B0B6B8',
    fontSize: 14,
  },
  removeCouponText: {
    color: '#0088B1',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 10,
    marginBottom: Platform.OS === 'ios' ? 10 : 0,
    marginRight: Platform.OS === 'ios' ? 10 : 0,
    textDecorationLine: 'underline',
  },
  retryButton: {
    backgroundColor: '#0088B1',
    borderRadius: 5,
    padding: 10,
  },
  retryButtonText: {
    color: 'white',
  },
  safeHeader: {
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  scrollContainer: {
    paddingBottom: 120,
  },
  selectedDot: {
    backgroundColor: '#0088B1',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
});
