import { Platform, StatusBar, StyleSheet } from 'react-native';
import { Fonts } from '../../styles/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingBottom: 120,
  },
  amountLabel: {
    fontSize: 10,
    color: '#161D1F',
    marginBottom: 2,
    fontFamily: Fonts.JakartaRegular,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e8f4f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  couponStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Platform.OS === 'ios' ? 0 : 12,
    borderRadius: 6,
    marginHorizontal: 12,
    marginTop: 12,
    backgroundColor: '#E8F4F7',
  },
  couponLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  couponText: {
    fontSize: 12,
    marginLeft: 6,
    lineHeight: 20,
    paddingVertical: Platform.OS === 'ios' ? 12 : 0,
    fontFamily: Fonts.JakartaSemiBold,
  },
  icon: {
    marginRight: 6,
  },
  deliveryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 15,
    marginTop: 20,
  },
  deliveryText: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#161D1F',
    marginBottom: 5,
  },
  mediCashCard: {
    height: 52,
    margin: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#B0B6B8',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F2F4F5',
  },
  mediCashLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mediCashText: {
    fontSize: 12,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#B0B6B8',
  },
  radioCircle: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#B0B6B8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  selectedDot: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: '#0088B1',
  },
  radioLabel: {
    fontSize: 14,
    color: '#B0B6B8',
  },
  billSummaryLabel: {
    fontSize: 18,
    fontFamily: Fonts.JakartaRegular,
    marginHorizontal: 12,
    marginTop: 16,
    color: '#161D1F',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amountText: {
    fontSize: 16,
    fontFamily: Fonts.JakartaBold,
    color: '#0088B1',
  },
  addressButton: {
    backgroundColor: '#0088B1',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  addressButtonText: {
    color: '#fff',
    fontSize: 10,
    fontFamily: Fonts.JakartaBold,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#fff',
  },

  headerRightIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  iconSpacing: {
    marginRight: 16,
  },
  safeHeader: {
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: 'red',
    marginBottom: 20,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: '#0088B1',
    padding: 10,
    borderRadius: 5,
  },
  retryButtonText: {
    color: 'white',
  },
  emptyCartContainer: {
    padding: 20,
    alignItems: 'center',
  },
  emptyCartText: {
    fontSize: 16,
    color: '#666',
    fontFamily: Fonts.JakartaSemiBold,
  },
  appliedCouponContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Platform.OS === 'android' ? 5 : 0,
    marginHorizontal: 20,
    backgroundColor: '#E8F4F7',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  appliedCouponLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  appliedCouponCode: {
    fontSize: 10,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#FFFFFF',
    marginLeft: 4,
  },
  appliedCouponText: {
    fontSize: 10,
    fontFamily: Fonts.JakartaRegular,
    color: '#E8F4F7',
    marginLeft: 8,
    marginTop: Platform.OS === 'ios' ? -5 : 0,
    paddingVertical: Platform.OS === 'ios' ? 5 : 0,
    marginBottom: Platform.OS === 'ios' ? 5 : 0,
  },
  removeCouponText: {
    fontSize: 10,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#0088B1',
    textDecorationLine: 'underline',
    marginRight: Platform.OS === 'ios' ? 10 : 0,
    marginBottom: Platform.OS === 'ios' ? 10 : 0,
  },
});
