import {StyleSheet} from 'react-native';
import {FontColors, Fonts} from '../../../styles/fonts';

const styles = StyleSheet.create({
  modal: {
    margin: 0,
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    maxHeight: '75%',
    minHeight: '5%',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  headerContainer: {
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 32,
  },
  title: {
    marginBottom: 12,
    fontSize: 24,
    fontFamily: Fonts.JakartaBold,
    color: FontColors.primary,
  },
  subtitle: {
    fontSize: 12,
    color: '#8E8E93',
    fontFamily: Fonts.JakartaRegular,
  },
  buttonContainer: {
    width: '100%',
    gap: 5,
    marginBottom: 20,
  },
  uploadOption: {
    width: '100%',
    paddingVertical: 12,
    display: 'flex',
    flexDirection: 'row',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: FontColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  uploadOptionText: {
    color: FontColors.primary,
    fontSize: 16,
    fontFamily: Fonts.JakartaRegular,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  dividerText: {
    paddingHorizontal: 16,
    color: '#666',
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
  },
  previewContainer: {
    width: '100%',
    marginTop: 12,
    // marginBottom: 20,
    // Removed maxHeight to allow expansion
  },
  filePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    marginBottom: 8,
  },
  imagePreview: {
    width: 40,
    height: 40,
    borderRadius: 4,
    marginRight: 10,
  },
  fileName: {
    flex: 1,
    fontFamily: Fonts.JakartaRegular,
    color: '#111827',
    marginRight: 10,
  },
  removeButton: {
    padding: 4,
  },
  actionButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 10,
    paddingTop: 10,
    backgroundColor: '#fff',
    marginBottom: 20,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#E5E7EB',
  },
  cancelButtonText: {
    color: '#111827',
    fontFamily: Fonts.JakartaSemiBold,
  },
  proceedButton: {
    backgroundColor: FontColors.primary,
  },
  proceedButtonText: {
    color: 'white',
    fontFamily: Fonts.JakartaSemiBold,
  },
  confirmationModal: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmationTitle: {
    fontSize: 18,
    fontFamily: Fonts.JakartaBold,
    color: '#111827',
    marginBottom: 8,
  },
  confirmationText: {
    fontSize: 14,
    fontFamily: Fonts.JakartaRegular,
    color: '#6B7280',
    marginBottom: 20,
    textAlign: 'center',
  },
  confirmationButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 10,
  },
  confirmationButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelConfirmButton: {
    backgroundColor: '#E5E7EB',
  },
  cancelConfirmButtonText: {
    color: '#111827',
    fontFamily: Fonts.JakartaSemiBold,
  },
  confirmButton: {
    backgroundColor: FontColors.primary,
  },
  confirmButtonText: {
    color: 'white',
    fontFamily: Fonts.JakartaSemiBold,
  },
  uploadMethodsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 8,
  },
  recentListContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    height: 175,
    padding: 10,
    marginTop: 8,
  },
  uploadCard: {
    flex: 1,
    height: 110,
    backgroundColor: FontColors.secondary,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  iconWrapper: {
    backgroundColor: '#C3E3EC',
    padding: 12,
    borderRadius: 50,
    marginBottom: 8,
  },
  methodLabel: {
    fontSize: 8,
    color: FontColors.textBlack,
    marginBottom: 12,
    fontFamily: Fonts.JakartaRegular,
  },
  successStrip: {
    position: 'absolute',
    bottom: 0,
    paddingVertical: 2,
    width: '100%',
    backgroundColor: '#50B57F',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successText: {
    fontSize: 8,
    color: '#FFFFFF',
    fontFamily: Fonts.JakartaRegular,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: Fonts.JakartaMedium,
    color: FontColors.textBlack,
    textAlign: 'left',
  },
  sectionTitleForUploaded: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: FontColors.textBlack,
    marginTop: 32,
    textAlign: 'left',
  },
  sectionSubtitle: {
    fontSize: 12,
    fontFamily: Fonts.JakartaRegular,
    color: '#6B7280',
    marginTop: 4,
  },
  horizontalScrollContainer: {
    paddingVertical: 10,
    paddingRight: 20,
  },
  uploadedFileCard: {
    width: 80,
    height: 100,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    marginRight: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  uploadedFileIcon: {
    width: 60,
    height: 60,
    borderRadius: 4,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  uploadedFileImage: {
    width: '100%',
    height: '100%',
  },
  uploadedFileRemove: {
    position: 'absolute',
    top: 8,
    right: 4,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 2,
  },
  uploadedFileStatus: {
    position: 'absolute',
    bottom: 8,
    left: 4,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 2,
  },
  uploadedImageContainer: {
    position: 'relative',
    width: 40,
    height: 40,
    marginRight: 10,
  },
  pdfIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 4,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  transparentCheckIcon: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 2,
  },
});

export default styles;
