import {StyleSheet, Dimensions} from 'react-native';
import {Fonts} from '../../styles/fonts';

const {height, width} = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F7F7',
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  container: {
    flex: 1,
    backgroundColor: '#F7F7F7',
  },
  backgroundDecoration: {
    position: 'absolute',
    top: -height * 0.15,
    right: -width * 0.2,
    width: width * 0.6,
    height: width * 0.6,
    borderRadius: width * 0.3,
    backgroundColor: '#E6F4F8',
    opacity: 0.5,
  },
  backgroundCircle: {
    position: 'absolute',
    top: height * 0.1,
    left: -width * 0.15,
    width: width * 0.4,
    height: width * 0.4,
    borderRadius: width * 0.2,
    backgroundColor: '#E6F4F8',
    opacity: 0.3,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: height * 0.1,
    paddingBottom: 40,
    alignItems: 'center',
  },
  iconContainer: {
    alignItems: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  iconWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#0088B1',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#0088B1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 2,
  },
  iconGlow: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#0088B1',
    opacity: 0.2,
    zIndex: 1,
  },
  title: {
    fontSize: 28,
    fontFamily: Fonts.JakartaBold,
    color: '#1A1A1A',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    fontFamily: Fonts.JakartaRegular,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
    maxWidth: '80%',
  },
  detailsCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  cardHeader: {
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#1A1A1A',
  },
  amountSection: {
    alignItems: 'center',
    paddingVertical: 20,
    marginBottom: 16,
  },
  amountLabel: {
    fontSize: 14,
    fontFamily: Fonts.JakartaRegular,
    color: '#64748B',
    marginBottom: 8,
  },
  amountValue: {
    fontSize: 32,
    fontFamily: Fonts.JakartaBold,
    color: '#0088B1',
  },
  separator: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 16,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  detailLabel: {
    fontSize: 14,
    fontFamily: Fonts.JakartaMedium,
    color: '#475569',
    flex: 1,
  },
  detailValue: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#1A1A1A',
    textAlign: 'right',
    flex: 1,
    marginLeft: 16,
  },
  actionButtons: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#0088B1',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  secondaryButtonText: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#0088B1',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#0088B1',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#0088B1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    marginBottom: 20,
  },
  primaryButtonText: {
    fontSize: 16,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#FFFFFF',
  },
  supportLink: {
    paddingVertical: 8,
  },
  supportText: {
    fontSize: 14,
    fontFamily: Fonts.JakartaRegular,
    color: '#64748B',
    textDecorationLine: 'underline',
  },
});
