import {Platform, StatusBar, StyleSheet} from 'react-native';
import {Fonts} from '../../styles/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    gap: 10,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e8f4f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    color: '#212121',
    fontFamily: Fonts.JakartaBold,
  },
  scrollView: {
    flex: 1,
    padding: 16,
    backgroundColor: '#F8F8F8',
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.JakartaBold,
    color: '#212121',
    marginBottom: 12,
  },
  contactTitle: {
    marginTop: 24,
  },
  formGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#606060',
    marginBottom: 8,
  },
  required: {
    color: 'red',
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    fontFamily: Fonts.JakartaRegular,
  },
  inputFilled: {
    backgroundColor: '#D3D7D8',
    borderWidth: 0,
  },
  inputFocused: {
    borderColor: '#0088B1',
    backgroundColor: '#E8F4F7',
  },
  errorText: {
    color: 'red',
    fontSize: 12,
    marginTop: 4,
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfWidth: {
    width: '48%',
  },
  addressTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  addressTypeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 20,
    backgroundColor: 'transparent',
    minWidth: 80,
  },
  selectedAddressType: {
    borderColor: '#0088B1',
    backgroundColor: '#0088B1',
  },
  addressTypeText: {
    fontSize: 10,
    color: '#000',
    marginLeft: 4,
    fontFamily: Fonts.JakartaRegular,
  },
  selectedAddressTypeText: {
    color: '#FFFFFF',
  },
  infoText: {
    fontSize: 12,
    color: '#757575',
    marginTop: 8,
    marginBottom: 24,
  },
  saveButton: {
    backgroundColor: '#0088B1',
    height: 52,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    padding: 12,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  disabledButton: {
    backgroundColor: '#cccccc',
    opacity: 0.7,
  },

  // Full Width Dropdown Styles
  fullWidthDropdownContainer: {
    marginBottom: 16,
    position: 'relative',
    zIndex: 1000,
    marginHorizontal: -16, // Extend to full width by negating container padding
  },
  fullWidthDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 48,
  },
  fullWidthDropdownContent: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',

    zIndex: 1001,
    maxHeight: 300,
  },
  dropdownContainer: {
    marginBottom: 16,
    position: 'relative',
    zIndex: 1000,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 48,
  },
  dropdownButtonText: {
    fontSize: 16,
    color: '#212121',
    fontFamily: Fonts.JakartaRegular,
    flex: 1,
  },
  dropdownContent: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderTopWidth: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1001,
    maxHeight: 300,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  dropdownItemText: {
    fontSize: 16,
    color: '#212121',
    fontFamily: Fonts.JakartaRegular,
    marginLeft: 12,
  },

  // Saved Address Item Styles
  savedAddressItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 8,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedSavedAddress: {
    borderColor: '#0088B1',
    borderWidth: 2,
    backgroundColor: '#F0F8FF',
  },
  savedAddressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  savedAddressInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
    flex: 1,
  },
  savedAddressType: {
    fontSize: 16,
    fontFamily: Fonts.JakartaBold,
    color: '#212121',
  },
  defaultBadge: {
    backgroundColor: '#0088B1',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 8,
  },
  defaultBadgeText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontFamily: Fonts.JakartaSemiBold,
  },
  savedAddressName: {
    fontSize: 14,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#212121',
    marginBottom: 4,
  },
  savedAddressText: {
    fontSize: 12,
    fontFamily: Fonts.JakartaRegular,
    color: '#606060',
    lineHeight: 16,
    marginBottom: 4,
  },
  savedAddressPhone: {
    fontSize: 12,
    fontFamily: Fonts.JakartaRegular,
    color: '#606060',
  },
  dropdownHeader: {
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 30,
  },
  inputError: {
    borderColor: '#FF4444',
  },
  dropdownHeaderTop: {
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 10,
  },
  dropdownHeaderOpen: {
    padding: 12,
    backgroundColor: '#E8F4F7',
    borderRadius: 8,
    marginBottom: 10,
  },
  dropdownHeaderText: {
    fontSize: 16,
    fontFamily: Fonts.JakartaSemiBold,
    color: '#000',
  },
  addressTypeDropdownOptions: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    marginTop: 5,
    zIndex: 10,
    position: 'absolute',
    top: 45,
    width: '100%',
  },
  addressTypeOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    backgroundColor: '#fff',
  },
});

export default styles;
