import { Platform, StatusBar, StyleSheet } from 'react-native';
import { Fonts } from '../../styles/fonts';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFF',
    flex: 1,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#E0E0E0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#e8f4f7',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  headerTitle: {
    color: '#212121',
    fontFamily: Fonts.JakartaBold,
    fontSize: 16,
  },
  scrollView: {
    backgroundColor: '#F8F8F8',
    flex: 1,
    padding: 16,
  },
  sectionTitle: {
    color: '#212121',
    fontFamily: Fonts.JakartaBold,
    fontSize: 16,
    marginBottom: 12,
  },
  contactTitle: {
    marginTop: 24,
  },
  formGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    color: '#606060',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
    marginBottom: 8,
  },
  required: {
    color: 'red',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E0E0',
    borderRadius: 8,
    borderWidth: 1,
    fontFamily: Fonts.JakartaRegular,
    fontSize: 16,
    height: 48,
    paddingHorizontal: 12,
  },
  inputFilled: {
    backgroundColor: '#D3D7D8',
    borderWidth: 0,
  },
  inputFocused: {
    backgroundColor: '#E8F4F7',
    borderColor: '#0088B1',
  },
  errorText: {
    color: 'red',
    fontSize: 12,
    marginTop: 4,
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfWidth: {
    width: '48%',
  },
  addressTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  addressTypeButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: '#000',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    minWidth: 80,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  selectedAddressType: {
    backgroundColor: '#0088B1',
    borderColor: '#0088B1',
  },
  addressTypeText: {
    color: '#000',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 10,
    marginLeft: 4,
  },
  selectedAddressTypeText: {
    color: '#FFFFFF',
  },
  infoText: {
    color: '#757575',
    fontSize: 12,
    marginBottom: 24,
    marginTop: 8,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#0088B1',
    borderRadius: 8,
    height: 52,
    justifyContent: 'center',
    marginBottom: 20,
    padding: 12,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  disabledButton: {
    backgroundColor: '#cccccc',
    opacity: 0.7,
  },

  // Full Width Dropdown Styles
  fullWidthDropdownContainer: {
    marginBottom: 16,
    marginHorizontal: -16,
    position: 'relative',
    zIndex: 1000, // Extend to full width by negating container padding
  },
  fullWidthDropdownButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E0E0',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  fullWidthDropdownContent: {
    backgroundColor: '#FFFFFF',
    left: 0,
    maxHeight: 300,
    position: 'absolute',
    right: 0,

    top: '100%',
    zIndex: 1001,
  },
  dropdownContainer: {
    marginBottom: 16,
    position: 'relative',
    zIndex: 1000,
  },
  dropdownButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E0E0',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownButtonText: {
    color: '#212121',
    flex: 1,
    fontFamily: Fonts.JakartaRegular,
    fontSize: 16,
  },
  dropdownContent: {
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderColor: '#E0E0E0',
    borderTopWidth: 0,
    borderWidth: 1,
    elevation: 5,
    left: 0,
    maxHeight: 300,
    position: 'absolute',
    right: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    top: '100%',
    zIndex: 1001,
  },
  dropdownItem: {
    alignItems: 'center',
    borderBottomColor: '#F0F0F0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownItemText: {
    color: '#212121',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 16,
    marginLeft: 12,
  },

  // Saved Address Item Styles
  savedAddressItem: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E0E0',
    borderRadius: 12,
    borderWidth: 1,
    elevation: 2,
    marginHorizontal: 8,
    marginVertical: 4,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  selectedSavedAddress: {
    backgroundColor: '#F0F8FF',
    borderColor: '#0088B1',
    borderWidth: 2,
  },
  savedAddressHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 8,
  },
  savedAddressInfo: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    marginLeft: 8,
  },
  savedAddressType: {
    color: '#212121',
    fontFamily: Fonts.JakartaBold,
    fontSize: 16,
  },
  defaultBadge: {
    backgroundColor: '#0088B1',
    borderRadius: 12,
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  defaultBadgeText: {
    color: '#FFFFFF',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 10,
  },
  savedAddressName: {
    color: '#212121',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 14,
    marginBottom: 4,
  },
  savedAddressText: {
    color: '#606060',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 4,
  },
  savedAddressPhone: {
    color: '#606060',
    fontFamily: Fonts.JakartaRegular,
    fontSize: 12,
  },
  dropdownHeader: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 30,
    padding: 12,
  },
  inputError: {
    borderColor: '#FF4444',
  },
  dropdownHeaderTop: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 10,
    padding: 12,
  },
  dropdownHeaderOpen: {
    backgroundColor: '#E8F4F7',
    borderRadius: 8,
    marginBottom: 10,
    padding: 12,
  },
  dropdownHeaderText: {
    color: '#000',
    fontFamily: Fonts.JakartaSemiBold,
    fontSize: 16,
  },
  addressTypeDropdownOptions: {
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderRadius: 5,
    borderWidth: 1,
    marginTop: 5,
    position: 'absolute',
    top: 45,
    width: '100%',
    zIndex: 10,
  },
  addressTypeOption: {
    backgroundColor: '#fff',
    borderBottomColor: '#E0E0E0',
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
});

export default styles;
