import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  View,
  Text,
  TouchableOpacity,
  Linking,
} from 'react-native';
import {ChevronLeft} from 'lucide-react-native';
import {useNavigation} from '@react-navigation/native';
import styles from './index.styles';

const TermsConditionsScreen: React.FC = () => {
  const navigation = useNavigation();

  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backBtn}
          onPress={() => navigation.goBack()}>
          <ChevronLeft size={24} color="#0088B1" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms & Conditions</Text>
      </View>

      <ScrollView
        contentContainerStyle={styles.container}
        showsVerticalScrollIndicator={false}>
        <Text style={styles.body}>
          The following are the Terms and Conditions, read together with the
          Privacy Policy, that govern your purchase and use of the products and
          services (the "Products") from Mediversal Healthcare Pvt Ltd. through
          the website gws@mediversal.in or “Mediversal” mobile application, and
          constitute a legally binding agreement, between you ("the Customer",
          the "User” or "the Caregiver") and gws@mediversal.in / “Mediversal”
          mobile app both of which are the online medium of the fully licensed
          Pharmacy of Mediversal Healthcare Pvt Ltd.{'\n\n'}
          In terms of Information Technology Act, 2000, this document is an
          electronic record. Being generated by a computer system it does not
          require any physical or digital signatures.{'\n\n'}
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries Guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of https://www.gwsmediversal.in
          or the application ‘Mediversal’.{'\n\n'}
          The domain name https://www.gwsmediversal.in/ (hereinafter referred to
          as ‘Website’) and the Mobile Application Mediversal (hereinafter
          referred to as ‘App’) bearing the registered address at Mediversal
          Super specialty Hospital (A unit of Mediversal Healthcare Pvt. Ltd),
          Doctors' Colony, Kankarbagh, Patna - 800 020, Bihar (hereinafter
          referred to as ‘Company’).{'\n\n'}
          For the purpose of these Terms of Service, wherever the context so
          requires the term ‘You’/ ‘User’ shall mean any natural or legal person
          who has downloaded and installed this Mobile Application (hereinafter
          referred to as ‘App’) and provided Registration Data while registering
          on the App or by simply visiting the Website by entering the domain
          name in any internet browser. Any services provided by the Website/App
          which do not require registration do not absolve you of the
          contractual relationship established by this Agreement.{'\n\n'}
          Wherever the context requires, the term ‘Doctor/registered medical
          practitioners’ shall mean any person permitted to practice medicine by
          the MCI (Medical Council of India) or any regional council for
          registration of Doctor/registered medical practitioners duly
          authorized by the government who will be verified and authenticated by
          us.{'\n\n'}
          By downloading and installing this App, you are bound by these Terms
          of Service and any other binding document as decided by the Company.
          You are requested to read them carefully before accepting the same and
          moving forward to using the App/Website.{'\n\n'}
          By visiting, viewing, accessing or otherwise using any of the services
          or information created, collected, compiled or submitted to
          www.gwsmediversal.in, you are deemed to have agreed to all the
          following Terms and Conditions of Sale/Service. So, before you use
          this Website/App, please read these Terms carefully as you agree to be
          bound by them. If you do not accept these Terms and Conditions, please
          do not use this App/Website.
        </Text>

        <Text
          style={styles.link}
          onPress={() =>
            Linking.openURL('https://gwsmediversal.in/term-and-conditions')
          }>
          Read the full Terms and Conditions here
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
};

export default TermsConditionsScreen;
